version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plataforma
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  api:
    build: ./apps/api
    command: npm run start:dev
    volumes:
      - ./apps/api:/usr/src/app
    ports:
      - '3333:3333'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/plataforma
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
  web:
    build: ./apps/web
    command: npm run dev
    volumes:
      - ./apps/web:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - api
volumes:
  db_data:
  redis_data: 